name: tryst
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_notch_bottom_bar: ^1.0.3
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^9.0.0
  calendar_timeline: ^1.1.3
  easy_date_timeline: ^2.0.6
  equatable: ^2.0.3
  firebase_core: ^3.0.0
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.7.0
  google_fonts: ^6.2.1
  meta: ^1.7.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/