// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_iz_dZ8JZsOjz319lAjVERCzguS33C3E',
    appId: '1:472956815604:web:235d9f41c3d224755636a1',
    messagingSenderId: '472956815604',
    projectId: 'tryst--development',
    authDomain: 'tryst--development.firebaseapp.com',
    storageBucket: 'tryst--development.firebasestorage.app',
    measurementId: 'G-B5LWG09P4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARNXhejHMFyXefue-VVW7zxudTM8tYh8s',
    appId: '1:472956815604:android:eb4021669a65cd475636a1',
    messagingSenderId: '472956815604',
    projectId: 'tryst--development',
    storageBucket: 'tryst--development.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsPH91miuG8OUEJXZhw2gZUcJuOa-BtzM',
    appId: '1:472956815604:ios:ef410153cee228c55636a1',
    messagingSenderId: '472956815604',
    projectId: 'tryst--development',
    storageBucket: 'tryst--development.firebasestorage.app',
    iosClientId: '472956815604-cn9n9hu61bkiqvi9v3eq154q6cmhoiih.apps.googleusercontent.com',
    iosBundleId: 'com.example.tryst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsPH91miuG8OUEJXZhw2gZUcJuOa-BtzM',
    appId: '1:472956815604:ios:ef410153cee228c55636a1',
    messagingSenderId: '472956815604',
    projectId: 'tryst--development',
    storageBucket: 'tryst--development.firebasestorage.app',
    iosClientId: '472956815604-cn9n9hu61bkiqvi9v3eq154q6cmhoiih.apps.googleusercontent.com',
    iosBundleId: 'com.example.tryst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt3th2gxUINffGukJrQTWNa1t6zRxt2Xc',
    appId: '1:472956815604:web:4a0a7bf82cddb1e75636a1',
    messagingSenderId: '472956815604',
    projectId: 'tryst--development',
    authDomain: 'tryst--development.firebaseapp.com',
    storageBucket: 'tryst--development.firebasestorage.app',
    measurementId: 'G-0WTY0Y9VQ6',
  );

}