name: "WakaTime Screenshot"
on:
  push: 
  schedule:
  - cron: "0 0 * * 5"
jobs:
  build:
    runs-on: "ubuntu-latest"
    
    permissions: 
      contents: write
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"

      - uses: actions/checkout@v4
      - run: |
          cd ./.github/workflows
          npm install
          node action.js
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "generated"
          git push



