name: "WakaTime Screenshot"
on:
  schedule:
  - cron: "0 12 * * 5"
jobs:
  build:
    runs-on: "ubuntu-latest"
    
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"

      - name: Install dependencies
        run: npm install
      
      - name: Run Screenshot
        run: npm run start

