name: "WakaTime Screenshot"
on:
  schedule:
  - cron: "0 0 * * 5"
jobs:
  build:
    runs-on: "ubuntu-latest"
    
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 18
      - name: RunWorkflow    
        run: cd ./workflows && npm i && node index.js && cd ..

      - name: GitFlow
        run: |
              git config user.name "github-actions[bot]"
              git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git add .
              git commit -am "generated"
              git push
